### ISSUE TITLE
It seems your submission was deleted.

### ISSUE THREAD

**Issue by fucnknown** [Fungie2134/AuthMod#1]
I managed to see your plugin in the 3 hours it was online. Was just about to download it for testing but the submission in Forge dissapeared.   
That was you or did something else happen?

In any case, could you compile a release?

Thanks

**Comment by Aang23** [comment]
It is normal, my page was lock because in moderation.

I made a stable release, which is in moderation, it should be available soon, I will tell you here !

**Comment by Aang23** [comment]
I'm uploading it.

**Comment by Aang23** [comment]
Look in the builds folder, the only file is the good build.
And I found a little bug because of a removed class. Correcting it.

**Comment by fucnknown** [comment]
Cool, will make some tests in a SkyFactory3 server. Will let you know.
Cheers

**Comment by Aang23** [comment]
Thanks ! The actual build is buggy with some mods, I am correcting it and testing on my own server and  I will let you know when done.

**Comment by Aang23** [comment]
Tested and confirmed to work with SkyFactory3, using the build I gave to you.
I doesn't work with my mods and it should be fixed quickly. But not today.

**Comment by fucnknown** [comment]
Odd.. Total crash on SkyFactory 1.0.9 (Stable) on login. Filed it as a new issue, will try to make a secondary server for tests :/

**Comment by Aang23** [comment]
Version 1.2 released, permission issue which needed to be OP to use command now fixed.

Next release will add a command to change password and a configuration file to disable commands like /see and some others.

**Comment by Aang23** [comment]
It now have a new command /changelogin as explained in the decription, and a config file to disable command in config/AuthMod.cfg : 1 to enable it, 0 to disable.
I added what you wanted. Now it is stable with no bugs, the next release will just add a little more config and it will be released.

**Comment by fucnknown** [comment]
Thank you for all the work!
