### ISSUE TITLE
Fakes players names

### ISSUE THREAD

**Issue by Aang23** [Fungie2134/AuthMod#10]
Do not use for bugs reports. Only to tell me if I forgot to add some fakes players names as default in the mod. Actually only these are default :
- Mekanism
- Extra Utilities 2

**Comment by hoblin** [comment]
`[PR_FAKE]` from Project Red

**Comment by Tander** [comment]
`[Minecraft]`
Seems its "official" Minecraft fakeplaer. Used by Actually Additions in 1.10.2

**Comment by Aang23** [comment]
Will be added in the next release.
Thanks!

**Comment by Aang23** [comment]
Closing. Entire rewrite coming.
