### ISSUE TITLE
Handling fake users and other things (Encryption)

### ISSUE THREAD

**Issue by LosTigeros** [Fungie2134/AuthMod#14]
You should add support for handling fake users by defining UUID of them.

For example `DiscordIntegration` mod defines a fake player by using UUID `828653ca-0185-43d4-b26d-620a7f016be6`. You can't define there fake names because names are not static.

And I would like to see an option in config to define which commands you could execute without logging in/registering.

Shouldn't passwords be encrypted? Java contains encrypting methods (for example SHA-256).

I could make an pull request but the repo isn't updated.

**Comment by Aang23** [comment]
The repo will be up-to-date in a few minutes.
Sorry for my late answer... I was working on hashing passwords (disabling the /see command).
All your request are being worked on and should be out soon, but unfortunately, not on Curse.

Thanks!

**Comment by Aang23** [comment]
Closing. Entire rewrite coming.
