### ISSUE TITLE
Authmod 1.7 1.10.2 / Unable to drop item

### ISSUE THREAD

**Issue by gigafunk** [Fungie2134/AuthMod#5]
1.7 break players ability to q , drop items, even after login.    Does with spongeforge, without sponge forge, with forge version 1.10.2 2281 and 2297. 

1.6 is awesome still   

below is only thing in the  log, i included the spam above in case, and then i removed the rfstuff, coree and other related mods and still, cant use q to drop item, and dragging out of gui into world deletes item. with sponge and perms and jei  in place it dupes items, if thats any clue. without sponge and perms and stuff and jei it just deletes em.

my custom npc item giver is also acting up and wont throw items at you. probably not related, ill edit this post and update when i get it all back together in a few mins.

there is lots of other mods, like over a hundered, so who knows....if you have specific tests i can do without ripping all the mods off my server and having a trash world, ill help. Maybe even something like that if i have some time.

Thanks for the great mod!

[01:37:32] [Server thread/DEBUG] [extrautils2/]: OTL: Encode Packet: com.rwtema.extrautils2.power.PowerManager$PacketPower
[01:37:32] [ForkJoinPool-1-worker-43/INFO] [OpenComputers/]: Running the latest OpenComputers version.
[01:37:32] [Netty Epoll Server IO #1/DEBUG] [extrautils2/]: OTL: Decode Packet: com.rwtema.extrautils2.network.packets.PacketUseItemAlt
[01:37:32] [Netty Epoll Server IO #1/DEBUG] [extrautils2/]: OTL: Handle Packet: com.rwtema.extrautils2.network.packets.PacketUseItemAlt : CLIENT
[01:37:32] [Netty Epoll Server IO #1/DEBUG] [extrautils2/]: OTL: Scheduling Packet: com.rwtema.extrautils2.network.packets.PacketUseItemAlt : CLIENT
[01:37:32] [Server thread/INFO] [STDOUT/]: [com.auth.mod.commands.RegisterCommand:func_184881_a:55]: A AuthMod operation failed !

i am not sure iof that failed was related or a bad password, i use autologin on my client. Ill try with out then as well, but that just fires text in chat when it reads a text string in chat (O/register /login) 

This was log entry before removal of rf jtools and all related core mods and addition rf mods...i gotta put my server back together so I cant test and more now, sorry to not be of much help.

edit

its been a long day/night now 1.6 is doing it...so its must be unique to another mod we have, i will report back when i habve mor einfo and i am deleteing the cfg and the passwords everytime

**Comment by Aang23** [comment]
Correcting it ! Thanks

**Comment by gigafunk** [comment]
1.5 works, 1.6 and 7 no go, i just noticed this update I guess. 
Hey, a cool feature the spigot auth plugin does is putting the logged out person in a special permission group and changing it back when they login. I figure perms may be hard cause i notice the forge perms are limited and different from the old bukkit world and sponge. Thats just pie in the sky stuff, just a flexible way to deal with random problems that may pop up...thing is, there are not any  I have foudn other than these updates.

 Also its able to port the player to spawn until they login as well, which I think yours may be able to do, i havent experimented with it yet, but i see the tp stuff in the newer cfgs. 

Thanks so much , this is a really awesome bit of work as is.  And you keep tweaking it. Bravo, Thanks again! It really helps me with my lil 10 person family server...

**Comment by Aang23** [comment]
The 1.7 got some normal bugs... related to a forgot block of code. ( Still beta )
If you want the player to be teleported to spawn before login I can add this feature.

Doing this with actual permissions plugins may be difficult, I will ask to Thusmose if he can do something to make it possible. But I could add a little permission cfg for non-logged players.
But only use autologin for /login, my /register command does not work the same way.
The authmod operation failed is maybe a permission issue when saving passwords, if you are under linux ( server side ) try to "chmod 0777" anythings, bug also just check if the passwords.properties exist, if yes, do not worry.

I made it for a comparable use, I own a big modded server which is in devellopement, and I needed that, and decided to make it public... Thanks!

**Comment by gigafunk** [comment]
no, thank you! This is great!!!! Thanks! thanks! thanks for shareing! First I cant say this enough.

the authmod operation failed was just anything related i could find in log to maybe help you with the dropping issue.  I am not having any problems with 1.5.  Just 1.6 and 1.7. 1.5 is good enough for me anyhow. I am in no rush, Your next build will probably be fine.   

Do i need to do anything for fakeplayers with your mod? I havent tested killerjoe yet to see if it workls, but you mentioned devving a modded server, so thought I would ask.

I dont think there is any need for special permission groups for unlogged people after further thought. if you can restrict unlogged players from doing anything with their stuff or commands or anything but /login or /register , and its powerfull enough to stop mods, then its perfect as is. No reason to add the complication.

also, if the get teleported to spawn it would further reduce potential griefing of otehr peoples stuff. But I am not sure if I would use it for now, so dont rush to put it in on my account. I was just giveing you ideas from some of the more featured auth plugins for spigot that you may or may not be aware of.

I have a fork of Autologin i am trying to get to build, the original repository is lacking the forge stuff. So i am trying to get a version that works so i can start changing a few things so it will work better. But it already works with your authmod.    And register works fine too. Even though it repeats password twice and yours doesnt take password twice. it works as is for my server. but i would like to change some stuff.   

And just so you know, the cant q drop item problem is there in 1.6 and 1.7 even without autologin. Its the first thing i removed when i tested.

**Comment by Aang23** [comment]
Do no worry about fake player, they do not call the PlayerLoggedInEvent, the one were my mod starts.

They just cannot drop / get hurt / move / use chat / use command / interact when no logged in, impossible to grief. 

I fixed the "Q" issue, the next release will be out soon.
