### ISSUE TITLE
Getting kicked when logged in by IP

### ISSUE THREAD

**Issue by Kakiharu** [Fungie2134/AuthMod#7]
I set the login time for a week and upon connecting to the server it says it connected successfully by IP.

However a little while later you still get kicked for "Too long to login".

[01:29:56] [Server thread/INFO]: Kakiharu left the game
[01:29:57] [Server thread/WARN]: handleDisconnection() called twice
[01:29:57] [Timer-1/INFO]: Kicked Kakiharu from the game: 'Too long to login !'

**Comment by Aang23** [comment]
Can I have the complete logs ?

**Comment by Aang23** [comment]
I understand what happened, corrected it ! Release will be out in a few hours.
Tanks for reporting !

**Comment by Aang23** [comment]
Done, fixed in 2.3.
Thanks !

**Comment by Kakiharu** [comment]
I'll give it a test. If I don't report back it will be working. Thank you!

**Comment by Aang23** [comment]
Thanks ! It should work, I had forgotten to add one line which disable kick if logged by IP.
